[features]
seeds = false
[programs.devnet]
gifportal = "HJSuWzbdcgqKZorB8MU3GdyUZa1bjbtwUx5mYPsGJXNY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/jia/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
